const ar = {
  //Register page
  Register: "تسجل دخول جديد",
  Register_msg: "قم بإنشاء حساب جديد اليوم.",
  Check_phone_msg: "تحقق من بريدك الإلكتروني لعرض الرمز الذي نرسله",
  fristName: "الأسم الأول",
  lastName: "الأسم الأخير",
  Iaccept_conditions: "أوافق على ",
  Iaccept_conditions2: "الشروط والأحكام",
  Have_an_account: "هل لديك حساب؟",
  Continue: "إستمر",
  Borrower: "صاحب سيارة",
  Car_rental: "تأجير سيارة",
  Wrong: "كلمة المرور لمرة واحدة خاطئة، حاول مرة أخرى ",

  //login page
  login_msg: "مرحبًا بعودتك !",
  ContinueWith: "تواصل مع",
  Login: " تسجل الدخول",
  remember_me: "تذكرنى",
  Signup: "تسجل دخول جديد",
  Google: "جوجل",
  Facebook: "فيس بوك",
  Dont_have_account: "ليس لديك حساب؟",
  number: "رقم",
  OR: "أو",
  send: "إرسال",
  //forgetPass page
  forgetPass: "هل نسيت كلمة السر",
  Forgetpassword: "نسيان كلمه السر",
  forget_msg: "ادخل رقم الهاتف الخاص بك",
  SendAgain: "إرسال مره أخرى",

  //otp page
  OTPTitle: "مصادقة",
  OTPmessage: "تحقق من بريدك الإلكتروني لعرض الرمز الذي نرسله",

  //Reset Password page
  ResetPassword: "اعاده كلمه المرور",
  Newpassword: "كلمه سر جديده ",
  Rewrite_new_password: "إعادة كتابة كلمة المرور الجديدة",
  privacy_policy: "سياسة الخصوصية",

  //Homepage
  Home: "الصفحة الرئيسية",
  About_us: "نبذه عن الشركة",
  About: "عنا",
  Blogs: "المدونة",
  Contact_us: "اتصل بنا",
  save: "احفظ",
  time: "وقت",
  withOur: "معنا",
  Eagles: "Eagles",
  car_rental: "لتأجير السيارات",
  Book_car: "حجز سيارة",
  Location: "موقع",
  Pick_up: "موعد البداية",
  Drop_of: "موعد النهاية",
  Search: "بحث",
  long_term: "رحلة طويلة",
  short_term: "رحلة قصيرة",
  return_point: "نقطة العوده",
  PlanTitle: "خطط لرحلتك الآن",
  headerTitle: "تأجير سيارات سريع وسهل",
  about: "عن الشركة",
  aboutTitle: "شغل محرك سيارتك ، وابدأ مغامراتك",
  aboutparagrah:
    "لدينا متخصصون ذوو خبرة تزيد عن عشر سنوات في توريد السيارات للإيجار. تهدف شركتنا إلى تقديم خدمات عالية الجودة من خلال مستشارينا ذوي الخبرة والمهارة في الأسواق المحلية، حيث تغطي خدماتنا مساحات كبيرة داخل مصر والإمارات العربية المتحدة.",
  learn_more: "معرفة المزيد",
  carName: "اسم السيارة",
  par1: " يمكنك العثور على مجموعة كبيرة ومتنوعة من السيارات يمكنك الاختيار من بينها ",
  par2: "سيقوم فريق مركز الاتصال على مدار 24 ساعة بالاتصال بك للحصول على سيارتك السحرية.",
  par3: "هذا هو الوقت المناسب لك للحصول على سيارة ذات جودة عالية",
  Select_Car: "اختر السياره",
  Contact_Operator: "اتصل بنا",
  Available_now: "متاح الان",
  Let_Drive: "لنقم بالقيادة",
  //BookNow
  BookNow: "احجز الآن",
  RentDream: "استأجر سيارة أحلامك",
  bookingparagrah: `أسست مجموعة هيونداي موتور رؤية جديدة، "معًا من أجل مستقبل أفضل". من أجل الوفاء بدورها ومسؤوليتها كشركة عالمية موثوقة. حددت شركة هيونداي موتور رؤيتها`,

  //rental
  rentaltitle: "وفّر الوقت مع شركة Eagles  لتأجير السيارات",
  rentalMessage: "أعلى السيارات. الموردين المحليين. دعم 24/7.",
  book_ride: "احجز الان ",
  New_information: "معلومات جديدة",
  //Our_blogs
  Our_blogs: "المقاله",
  Reviewed_People: "تقييم العملاء",
  Clients_testimonials: "اراء العملاء",
  Clients_reviews: `إنها دائمًا تجربة إيجابية عند الاستئجار لديكم. فريق العمل محترف للغاية وفعال ويبتسم دائمًا. وأشعر دائمًا بالترحيب والتقدير.
  الإدارة سريعة دائمًا في حل أي مشكلة في أي وقت. كفاءتهم واحترافهم يجعل من خياري الأول.`,
  //FAQ
  FAQ: "أسئله",
  Frequently_Questions: "الاسئلة الشائعة",
  FQUMessage:
    "هل لديك سؤال عن أي شيء؟ يمكنك العثور على الإجابة أدناه أيضًا    يمكنك الاتصال بنا لمزيد من البيانات ",
  qus1: "هل يجب عليك فحص سيارتك قبل رحلة طويلة؟",
  qus2: "كم يجب أن يكون عمري لاستئجار سيارة؟",
  qus3: "كيف يمكنني العثور على أسعار تأجير السيارات المنخفضة هذه؟",
  answerQue:
    "آخر شيء يريده أي شخص عندما يكون في رحلة على الطريق هو عطل ميكانيكي في سيارته. إن الانهيار في بيئة غير مألوفة هو الأسوأ. إن أخذ سيارتك لإجراء فحص سريع من ميكانيكي مؤهل يمكن أن يوفر عليك صداعًا كبيرًا في المستقبل. سوف يقوم الميكانيكي بفحص الإطارات والفرامل والبطارية والسوائل والمحرك والأضواء والمساحات بسرعة للتأكد من أن كل شيء يعمل بسلاسة.",
  //DownloadTitle
  DownloadTitle: "قم بتنزيل تطبيقنا للحصول   علي كامل الخدمات المتاحة",
  Downloadparagrah:
    "تقديم خدمات تأجير السيارات لجميع الفئات الاجتماعية مثل  شركات الأمن والبنوك والأدوية  الشركات، وجميع الجنسيات مع مجموعة كبيرة ومتنوعة من الميزات",
  //Footer
  Terms_conditions: "الأحكام والشروط",
  Privacy_policy: "سياسة الخصوصية",
  How_works: "كيف يعمل",
  Support: "الدعم",
  Top_cars: "أفضل ماركات السيارات",
  Nissan: "نيسان",
  BMW: "بي إم دبليو",
  Honda: "هوندا",
  Audi: "أودي",
  Range_Rover: "رينج روفر",
  Join_community: "انضم إلى مجتمعنا",

  //MostFast
  most_fast: "أسرع سيارة في عام 2023",
  egypt_Free: "مرحبا بكم في مصر-السفر الحر",
  Popular_News: "أخبار شعبية",
  Related_News: "أخبار ذات صلة",

  //PrivacyPolicy
  PrivacyPolicy: "سياسة الخصوصية",

  //about us
  More_info: "مزيد من المعلومات",
  about_us_page: "عن شركتنا",
  Eagles_Car: "تأسست شركة Eagles car",
  messabout1:
    "تأسست شركة إيغلز لتأجير السيارات في ديسمبر 2015 على يد مجموعة من موردي السيارات. لدينا متخصصون ذوو خبرة تزيد عن عشر سنوات في توريد السيارات للإيجار.",
  paragabout1:
    "لدينا متخصصون ذوو خبرة تزيد عن عشر سنوات في توريد السيارات للإيجار. تهدف شركتنا إلى تقديم خدمات عالية الجودة من خلال مستشارينا ذوي الخبرة والمهارة في الأسواق المحلية، حيث تغطي خدماتنا مساحات كبيرة داخل مصر. يعتمد نشاطنا التجاري على نظام الإيجار المالي لأي عدد من السيارات، مع نظام قصير وطويل الأمد، ومتابعة صيانة السيارات وخدمة ما بعد التأجير لعملائنا. لدينا نظام لمراقبة الجودة لمراقبة ومتابعة أي شكوى وإيجاد حلاً لها.",
  paraabout2:
    "شركة إيغلز مهتمة بعملائها، حيث نقدم خطة تخصيصية لك وفقًا لميزانيتك.",
  Our_Mission: "مهمتنا",
  message_Mission1:
    "زيادة توسعنا في مكاتبنا لتغطية جميع احتياجات العملاء في جميع أنحاء مصر والتوسع في الشرق الأوسط بأكمله",
  message_Mission2:
    "نسعى جاهدين لتطوير خدماتنا باستمرار لتحقيق أفضل رضى العملاء. رؤيتنا المتقدمة هي هدفنا",
  message_Mission3:
    "حيث نسعى إلى توفير عدة طرق لإرضاء العميل وحرصنا على تقديم أفضل برامج تأجير السيارات",
  message_Mission4:
    "ونحرص على تلبية جميع متطلبات العميل من حيث جودة السيارات والخدمة المقدمة، ونسعى جاهدين لحل جميع العقبات التي تواجه العملاء.",
  Our_vision: "رؤيتنا",
  paravision:
    "تقديم خدمات تأجير السيارات لجميع الفئات الاجتماعية، مثل شركات الأمان، والبنوك، وشركات الأدوية، وجميع الجنسيات للمستثمرين الأجانب والسياح. نقدم جميع وسائل النقل، سواء كانت سيارات كوبيه، سيدان، دفع رباعي، أو سيارات لعدد أكبر من الركاب. نسهل إجراءات العقد، ونلبي احتياجات العملاء، ونضمن باستمرار راحتهم، ونوفر سيارات عالية الجودة، ونتابع صيانة السيارات بانتظام عن طريق تفويض السيارة المخصصة لهم، ونضمن تقديم أفضل الخيارات حتى نكون عند توقعات العملاء.",
  Our_Team: "فريقنا",
  Our_Service: "خدمتنا",
  Service1: ' الشركات الدوائية العالمية مثل "نوفو نورديسك".',
  Service2: "خدمات الإعلان الإلكتروني مثل OLX.",
  Service3: "قطاع شركات النفط.",
  Service4:
    "بعض البنوك التي نخدمها ولدينا حسابات فيها، مثل بنك قطر الوطني وبنك التجارة والتنمية الدولي.",
  Service5: "قطاع شركات الغاز الطبيعي",

  How_it_works: "كيف تعمل",
  view_detailes: "عرض تفاصيل تأجير السيارات",
  View: "عرض",
  Keep_touch: "ابقى على تواصل معنا",
  Name: "اسم",
  Mobile_number: "رقم الهاتف المحمول",
  Subject: "موضوع",
  Message: "رسالة",
  Contact_Info: "معلومات الاتصال",
  Phone_number: "رقم الهاتف",
  I_accept: "اوافق علي",
  Email: "بريد إلكتروني",
  password: "كلمه المرور",
  facebook: "فيسبوك",
  Social_media_contacts: "وسائل التواصل الاجتماعي ",
  Available: "متاح",
  What_looking: "ما الذي تبحث عنه؟",
  Search_filter: "البحث عن طريق الفلتر",
  Reset_all: "اعادة الفلترة",
  Car_type: " نوع السيارة",
  Car_model: "طراز السيارة",
  Year_model: "سنة الانشاء",
  Number_seat: "عدد المقاعد",
  Price_range: "التقييم",
  Rating: "تقييم",
  Apply: "التقديم",
  Recommended_cars: "السيارات الموصى بها",
  New_data: "بيانات جديدة",
  Car_details: "تفاصيل السيارة",
  Send_request: "ارسل طلب",
  Show_more: "",
  requiredFiled: "هذالحقل مطلوب",
  requiredFiledemail: "",
  phone: "الهاتف",
  Logout: "تسجيل خروج",
  Return_point: "نقطة العوده",
  Car_condition: "حالة السيارة",
  paraFooter: "متخصصون بخبرة أكثر من عشر سنوات في  توريد سيارات للتأجير.",
  with_driver: "بسائق",
  Without_driver: "بدون سائق",
  //Profile
  profile: "حسابك الشخصى",
  Basic_information: "معلومات اساسية",
  Save_changes: "حفظ التغير",
  FirstName: "الاسم الاول",
  LastName: "اسم العائلة",
  Nationality: "الجنسية",
  ID: "رقم البطاقه",
  Date_of_birth: "تاريخ الميلاد",
  Primary_phone_number: "رقم الهاتف الرئيسي",
  Secondary_phone_number: "رقم الهاتف التانى",
  Old_Password: "كلمة المرور القديمة",
  New_Password: "كلمة المرور الجديدة",
  Rewrite_new_Password: "أعد كتابة كلمة المرور الجديدة",
  Change_password: "تغيير كلمة المرور",
  Driver_License: "رخصة السائق",
  License_Number: "رقم الرخصة",
  Issuance_Date: "تاريخ الإصدار",
  Expiration_Date: "تاريخ انتهاء الصلاحية",
  Country_Issue: "بلد الإصدار",
  Driver_Phone_Number: "رقم هاتف السائق",
  Driver_license: "رخصة قيادة",
  Borrowing_verification: "التحقق من الاقتراض",
  Account_not_verified: "لم يتم التحقق من الحساب",
  messageAccount_not_verified:
    "يرجى إثبات أنك مقترض لمواصلة تأجير السيارات في مصر.",
  Identity_document: "وثيقة الهوية",
  messageIdentity_document:
    "تأكد من أن الهوية بتنسيق PDF أو JPG وبحد أقصى لحجم الملف 5 ميجابايت.",
  upload: "رفع",
  drivingEffect:
    "هل تم تغريمك من قبل بسبب القيادة تحت تأثير الكحول أو المخدرات",
  yearsDriving: "منذ كم سنة وأنت تقود السيارة؟",
  Verify: "يؤكد",
  add: "إضافه",
  Add_car: "أضف سيارتك",
  messageAdd_car: "لم تقم بإضافة أي سيارة بعد، لذا حاول إضافة سيارتك الآن أولا",
  Car_Information: "معلومات السيارة",
  Car_title: "عنوان السيارة",
  Make: "يصنع",
  Model: "نموذج",
  Year: "سنة",
  Number_Seats: "عدد المقاعد",
  Number_Doors: "عدد الأبواب",
  Fuel_Type: "نوع_الوقود",
  Transmission: "الانتقال",
  Mileage: "عدد الأميال",
  Color: "اللون",
  Car_Description: "وصف السيارة",
  Car_Description_message: "يمكنك أن تكتب هنا أي شيء عن سيارتك",
  Finish_later: "لاحقا",
  Next_step: "الخطوة التالية",
  Country_registeration: "بلد التسجيل",
  City: "المدينة",
  Plate_number: "رقم اللوحة",
  License_expiration_date: "تاريخ انتهاء الترخيص",
  Upload_Papers_car_license: "تحميل أوراق رخصة السيارة",
  Insurance: "تأمين",
  Insurance_yearly_cost: "تكلفة التأمين السنوية",
  Insurance_excess_value: "القيمة الزائدة للتأمين",
  Upload_Papers_car: "تحميل أوراق لسيارتك",
  message_Upload_Papers_car:
    "التأكد من الهوية بصيغة PDF أو JPG وبحد أقصى لحجم الملف 5 ميجابايت،",
  message_Upload_Papers_car_required: "الصور المطلوبة هي 6 صور.",
  Recommended_daily_price: "السعر اليومي الموصى به",
  Our_Recommended_daily_price: "السعر اليومي الموصى به هو",
  Our_Recommended_daily_price_number: "250 جنيه مصري/اليوم",
  Market_value_your_car: "القيمة السوقية لسيارتك",
  SELECT_HOW_WANT: "اختر الطريقة التي تريد بها إدراج سيارتك",
  Short_term: "المدى القصير",
  Short_term_mess: "قم بإدراج سيارتك لفترة قصيرة من 3 أيام إلى 3 أشهر",
  Long_term: "المدى القصير",
  Long_term_mess: "قم بإدراج سيارتك لفترة قصيرة من 3 أشهر إلى 3 سنوات",
  With_driver: "مع السائق",
  Publish: "نشرها",
  Finish_now: "انهاء الأن",
  Send_request_again: "أرسل الطلب مرة أخرى",
  Add_promotion: "أضف رمز الترويج الخاص بك",
  with_getting_new_users: "مع سوف يساعد في الحصول على مستخدمين جدد.",
  PromotionCode: "كود الترويجي",
  Use_fawery_payement: "استخدم طرق الفوري لاستخدام الدفع",
  Ensure_account_payment_methods_ways:
    "تأكد من أن لديك حسابًا لاستخدام طرق الدفع هذه",
  Click_followed_button_copy_link: "انقر فوق الزر المتبع أو انسخ الرابط",
  link_fawry: "وهذا رابط فوري",
  Notification: "الإشعارات",
  See_more_notifications: "رؤية المزيد من الإشعارات",
  See_more_Chats: "رؤية المزيد من الرسائل",
  Chats: "الرسائل",
  Send_message: "أرسل رسالة",
  List_your_car: "قائمة سيارتك",
  location: "المكان",
  Upload_Papers: "تحميل الأوراق",
  My_account: "حسابي",
  My_cars: "سياراتي",
  My_borrowings: "قروضي",
  My_requests: "طلباتي",
  Personal_information: "معلومات شخصية",
  Borrowing: "الاقتراض",
  All_Requests: "جميع الطلبات",
  Confirmed_request: "طلب مؤكد ",
  Car_information: "معلومات السيارة",
  Parking_address: "مكان السيارات",
  Car_license: "رخصة السيارة",
  Photo_and_prices: "الصور والأسعار",
  Promotions: "الترقيات",
  Payement: "الدفع",
  Choose_Your_Type: "اختر النوع الخاص بك",
  Choose_Car_model: "اختر توع السيارة",
  Choose_Number_seat: "ختر رقم المقعد",
  Maximum: "أقصى ",
  Minimum: "الحد الأدنى",
  sendRequest: "ارسل طلب",
  StartDate: "تاريخ البدء",
  add_car: "إضافه  عربيه",
  most_popular: "الأكتر شيوعا",
  Cars_Slug: " ",
  NameCarsOrBrands: "اسم العربية او البراند",
  message: "رساله",
  byBrand: "إبحث بإسم العلامة التجارية",
  Pick_up_Location: "اختر موقعا",
};
export default ar;
