const en = {
  //Register page
  Register: "Register",
  Register_msg: "Create new account today.",
  Check_phone_msg: "Check your email to view the code that we send",
  fristName: "Frist name",
  lastName: "Last name",
  Iaccept_conditions1: "I accept the ",
  Iaccept_conditions2: "terms and conditions",
  Have_an_account: "Have an account ?",
  Continue: "Continue",
  Borrower: "Borrower",
  Car_rental: "Car rental",
  OTP: "OTP",

  //login page
  Login: "Log in",
  login_msg: "Welcome back !",
  ContinueWith: "Continue with",
  remember_me: "Remeber me",
  Signup: "Sign up",
  forgetPass: "Forget password?",
  Google: "Google",
  Facebook: "Facebook",
  Dont_have_account: "Don’t Have an account ? ",
  number: "Number",
  OR: "OR",
  send: "Send",
  Wrong: "Wrong otp, try again ",

  //forgetPass page
  Forgetpassword: "Forget password",
  forget_msg: "Enter your phone number to change your password",
  SendAgain: "Send again",
  password: "Password",
  //otp page
  OTPTitle: "OTP Authentication",
  OTPmessage: "Check your email to view the code that we send",

  //Reset Password page
  ResetPassword: "Reset Password",
  Newpassword: "New password",
  Rewrite_new_password: "Rewrite new password",
  privacy_policy: "privacy Policy",

  //Homepage
  Home: "Home",
  About_us: "About us",
  About: "About",
  Blogs: "Blog",
  Contact_us: "Contact us",
  save: "Save",
  time: "Time",
  withOur: "with our",
  Eagles: "Eagles",
  car_rental: "car rental",
  Book_car: "Book a car",
  Location: "Location",
  Pick_up: "Pick up",
  Drop_of: "Drop of",
  Search: "Search",
  long_term: "Long Term",
  short_term: "Short Term",
  return_point: "Return point",
  PlanTitle: "Plan your trip now",
  headerTitle: "Quick & easy car rental",
  par1: "You can find a huge variety of cars you can select from them",
  par2: "Our 24 h call center team will contact with you to get your magic car",
  par3: "This is your time to get a high quality car",
  Select_Car: "Select Car",
  Contact_Operator: "Contact Operator",
  Let_Drive: "Let's Drive",
  about: "About company",
  aboutTitle: "You start the engine and your adventure begins",
  aboutparagrah: `We Have Specialists with More Than Ten Years Of Experience in
    Supplying Cars for Renting.
    Our company aims to provide high quality services Through our
    experienced and skilled consultants in the local markets, where our
    services cover huge areas inside Egypt and UEA`,
  learn_more: "learn more",
  carName: "car name",
  BookNow: "Book now",
  RentDream: "Rent your dream car",
  bookingparagrah:
    "Hyundai Motor Group established a new vision, “Together for a better future.” in order to fulfill its role and responsibility as a trusted global firm. Hyundai Motor Company defined its vision",
  rentaltitle: "Save Time with our Eagles car rental ",
  rentalMessage: "Top Airports. Local Suppliers. 24/7 Support.",
  book_ride: "Book Ride",
  New_information: "New information",
  Our_blogs: "Our blogs",
  Reviewed_People: "Reviewed by People",
  Clients_testimonials: "Clients' Testimonials",
  Clients_reviews:
    "It is always a positive experience when renting from your 5th street location. The staff is very professional and efficient and always smiling. And I always feel welcome and appreciated. The management is always prompt to solve any issue at any moment. Their efficiency and professionalism makes it my number one choice.",
  FAQ: "FAQ",
  Frequently_Questions: "Frequently Asked Questions",
  FQUMessage:
    "Use securing confined his shutters. Delightful as he it acceptance an solicitude discretion reasonably.Carriage we husbands advanced an perceive greatest.",
  qus1: "Should You Get Your Car Checked Before A Long Trip?",
  qus2: "How old do I need to be to rent a car?",
  qus3: "How do I find such low rental car prices?",
  answerQue:
    "The last thing anyone wants when they are going on a road trip is a mechanical failure of their vehicle. Being broken down in unfamiliar surroundings is the worst. Taking your vehicle in for a quick inspection from a qualified mechanic can save you a major headache down the line. A mechanic will quickly look over your tires, brakes, battery, fluids, engine, lights, and wipers to make sure everything is running smoothly.",
  //DownloadTitle
  DownloadTitle: "Download our app to get most out of it",
  Downloadparagrah:
    "Providing car rental services to all social groups, such security companies, banks as pharmaceutical companies, and all nationalities with a huge variety of features",

  //Footer
  Terms_conditions: "Terms and conditions",
  Privacy_policy: "Privacy policy",
  How_works: "How it works",
  Support: "Support",
  Top_cars: "Top Cars Brands",
  Nissan: "Nissan",
  BMW: "BMW",
  Honda: "Honda",
  Audi: "Audi",
  Range_Rover: "Range Rover",
  Join_community: "Join our community",
  Available_now: "Available now",

  //MostFast
  most_fast: "The most fast car in 2023",
  egypt_Free: "Welcome To Quarantine-Free Travel",
  Popular_News: "Popular News",
  Related_News: "Related News",

  //PrivacyPolicy
  PrivacyPolicy: "Privacy Policy",

  //about us
  More_info: "More info",
  about_us_page: "Our Company",
  Eagles_Car: "Eagles Car",
  messabout1: "Was Established on December 2015 by a group of cars Suppliers.",
  paragabout1:
    "We Have Specialists with More Than Ten Years Of Experience in Supplying Cars for Renting. Our company aims to provide high quality services Through our experienced and skilled consultants in the local markets, where our services cover huge areas inside egypt. Our Business Based on the Financial lease system for any numbers of cars, with short and long term system, car maintenance follow up and post rental service for our customers. We have quality control system in order to monitor and receive any complaint solved. ",
  paraabout2:
    "United Eagles car about their clients, where we offer a customization plan for you according to your budget.",
  Our_Mission: "Our Mission",
  message_Mission1:
    "Increasing office expansions to cover all customer equirements throughout Egypt and expanding",
  message_Mission2:
    " in the Middle East as a whole, striving to continuously develop our services to reach the",
  message_Mission3:
    " best customer satisfaction, Advanced vision is our goal Making multiple ways to satisfy the customer and keen to provide the best car",
  message_Mission4: ` rental programs, and being keen to meet all the customer's
    requirements in terms of the quality of cars and
    the service provided, and striving to solve all
    obstacles facing customers.`,
  Our_vision: "Our vision",
  paravision: `Providing car rental services to all social groups, such
security companies, banks
as pharmaceutical
companies, and all nationalities of foreign investors
and 
tourists, providing all transportation, whether it is
"Coupe, Sedan, SUV, vehicle for more passengers
too".
Facilitating contract procedures, providing customers'
requirements, constantly ensuring their comfort,
providing cars of the best quality, following up on
periodic maintenance of cars by delegating the car
assigned to them, and ensuring that we provide the best
options so that we are at the best of the customer's
expectations.`,
  Our_Team: "Our Team",
  Our_Service: "Our Service",
  Service1: `nternational pharmaceutical companies such as "novonordisk"`,
  Service2: "Electronic advertising services OLX",
  Service3: "Oil companies sector",
  Service4:
    "Some of the banks we serve and have our accounts QNB bank, CIB bank",
  Service5: "Natural gas companies sector",
  How_it_works: "How it works",
  view_detailes: "View car rental details ?",
  View: "View",
  Keep_touch: "Keep in touch with us",
  Name: "Name",
  Mobile_number: "Mobile number",
  Subject: "Subject",
  Message: "Message",
  Contact_Info: "Contact Info",
  Phone_number: "Phone number",
  Email: "Email",
  I_accept: "I accept the",
  facebook: "facebook",
  Social_media_contacts: "Social media contacts",
  Available: "Available",
  What_looking: "What are you looking for?",
  Search_filter: "Search by filter",
  Reset_all: "Reset All",
  Car_type: "Car type",
  Car_model: "Car model",
  Year_model: "Year model",
  Number_seat: "Number seat",
  Price_range: "Price range",
  Rating: "Rating",
  Apply: "Apply",
  Recommended_cars: "Recommended cars",
  New_data: "New data",
  Car_details: "Car details",
  Send_request: "Send request",
  Show_more: "Show more",
  requiredFiled: "this Filed is required",
  requiredFiledemail: "this filed must be email",
  phone: "phone",
  Logout: "Log out",
  Return_point: "Return point",
  Car_condition: "Car Condition",
  paraFooter:
    "Specialists with More Than Ten Years Of Experience in Supplying Cars for Renting.",
  with_driver: "With driver",
  Without_driver: "Without driver",
  Notification: "Notification",
  //profile
  profile: "Profile",
  Basic_information: "Basic information",
  Save_changes: "Save changes",
  FirstName: "First Name",
  LastName: "Last Name",
  Nationality: "Nationality",
  ID: "ID",
  Date_of_birth: "Date of_birth",
  Primary_phone_number: "Primary phone number",
  Secondary_phone_number: "Secondary phone number",
  Old_Password: "Old Password",
  New_Password: "New Password",
  Rewrite_new_Password: "Rewrite new Password ",
  Change_password: "Change password",
  Driver_License: "Driver's License",
  License_Number: "License Number",
  Issuance_Date: "Issuance Date",
  Expiration_Date: "Expiration Date",
  Country_Issue: "Country Of Issue",
  Driver_Phone_Number: "Driver's Phone Number",
  Driver_license: "Driver license",
  Account_not_verified: "Account not verified",
  messageAccount_not_verified:
    "Please verify yourself as a borrower to continue rent cars in Egypt.",
  Identity_document_face: "Identity document (face):",
  Identity_document_back: "Identity document (back):",
  messageIdentity_document:
    "Make sure to the identity in a PDF or JPG format with maximum file size 5 MB.",
  upload: "upload",
  drivingEffect:
    "Were you ever fined before for driving under the effect of Alchol or drugs?",
  yearsDriving: "For how many years have you been driving?",
  Verify: "Verify",
  add: "Add",
  Add_car: "Add your car",
  messageAdd_car: "You didn’t add any car yet, so try adding your first now",
  Car_Information: "Car Information",
  Car_title: "Car title",
  Make: "Make",
  Model: "Model",
  Year: "Year",
  Number_Seats: "Number of Seats",
  Number_Doors: "Number of Doors",
  Fuel_Type: "Fuel Type",
  Transmission: "Transmission",
  Mileage: "Mileage",
  Color: "Color",
  Car_Description: "Car Description",
  Car_Description_message: "You can write here anything about your car",
  Finish_later: "Finish later",
  Next_step: "Next step",
  Country_registeration: "Country of registeration",
  City: "City",
  Plate_number: "Plate number",
  License_expiration_date: "License expiration date",
  Upload_Papers_car_license: "Upload Papers for car license",
  Insurance_yearly_cost: "Insurance yearly cost",
  Insurance_excess_value: "Insurance excess value ",
  Upload_Papers_car: "Upload Papers for your car",
  message_Upload_Papers_car:
    "Make sure to the identity in a PDF or JPG format with maximum file size 5 MB,",
  message_Upload_Papers_car_required: "required images are 6 images.",
  Recommended_daily_price: "Recommended daily price",
  Our_Recommended_daily_price: "Our Recommended daily price is",
  Our_Recommended_daily_price_number: "250 EGP/Day",
  Market_value_your_car: "Market value of your car",
  SELECT_HOW_WANT: "SELECT HOW YOU WANT TO LIST YOUR CAR",
  Short_term: "Short term",
  Short_term_mess: "List your car for short period from 3 days to 3 months",
  Long_term: "Long term",
  Long_term_mess: "List your car for short period from 3 months to 3 years",
  With_driver: "With driver",
  Publish: "Publish",
  Finish_now: "Finish now",
  Send_request_again: "Send request again",
  Add_promotion: "Add your promotion code",
  with_getting_new_users: "with will help getting new users.",
  PromotionCode: "Promotion code",
  Use_fawery_payement: "Use fawery ways to use payement",
  Ensure_account_payment_methods_ways:
    "Ensure you have an account to use this payment methods ways",
  Click_followed_button_copy_link:
    "Click the followed button or copy the link:",
  link_fawry: "This is the link of fawry",
  See_more_notifications: "See more notifications",
  See_more_Chats: "See more chats",
  Chats: "Chats",
  Send_message: "Send message",
  List_your_car: "List your car",
  location: "location",
  Upload_Papers: "Upload Papers",
  My_account: "My account",
  My_cars: "My cars",
  My_borrowings: "My borrowings",
  My_requests: "My requests",
  Payement: "Payement",
  Personal_information: "Personal information",
  Borrowing_verification: "Borrowing verification",
  All_Requests: "All Borrowings",
  Confirmed_request: "Confirmed Borrowings ",
  Car_information: "Car information",
  Parking_address: "Parking address",
  Car_license: "Car license",
  Photo_and_prices: "Photo and prices",
  Promotions: "Promotions",
  Choose_Your_Type: "Choose Your Type",
  Choose_Car_model: "Choose Car model",
  Choose_Number_seat: "Choose Number seat",
  Maximum: "Maximum ",
  Minimum: "Minimum",
  license_number: "License Number",
  sendRequest: "send Request",
  StartDate: "Start Date",
  All_Car: "All Cars",
  Confirmed_Car: "Confirmed Cars",
  add_car: "Add Car",
  most_popular: "Most Popular",
  Cars_Slug: "Cars Slug",
  NameCarsOrBrands: "Name Car Or Brands",
  serach_car: "Search For A Car",
  byBrand: "Find By Brand",
  Book_car: "Book this car",
  Pick_up_Location: "Pick-up Location",
};

export default en;
